Replace tabs with spaces

diff --git a/bin/mkvm-rm b/bin/mkvm-rm
--- a/bin/mkvm-rm
+++ b/bin/mkvm-rm
@@ -5,15 +5,15 @@ set -ue
 instances=("$@")
 
 if [ "${#instances[@]}" -eq 0 ] && [ -n "${MKVM_INSTANCE:-}" ]; then
-	instances+=("$MKVM_INSTANCE")
+    instances+=("$MKVM_INSTANCE")
 fi
 
 for instance in "${instances[@]}"; do
-	vm_dir="$MKVM_ROOT/machines/$instance"
-	if [ ! -d "$vm_dir" ]; then
-		printf "machine not found: %s\n" "$instance" >&2
-		exit 1
-	fi
-	(cd "$vm_dir" && vagrant destroy)
-	rm -rf "$vm_dir"
+    vm_dir="$MKVM_ROOT/machines/$instance"
+    if [ ! -d "$vm_dir" ]; then
+        printf "machine not found: %s\n" "$instance" >&2
+        exit 1
+    fi
+    (cd "$vm_dir" && vagrant destroy)
+    rm -rf "$vm_dir"
 done
diff --git a/bin/mkvm-start b/bin/mkvm-start
--- a/bin/mkvm-start
+++ b/bin/mkvm-start
@@ -4,8 +4,8 @@ set -ue
 
 DEFAULT_DISTRO="arch"
 declare -A BOXES=(
-	["arch"]="archlinux/archlinux"
-	["ubuntu"]="ubuntu/focal64"
+    ["arch"]="archlinux/archlinux"
+    ["ubuntu"]="ubuntu/focal64"
 )
 
 name="${MKVM_INSTANCE:-}"
@@ -15,18 +15,18 @@ ports=()
 mounts=()
 
 while [ "$#" -ne 0 ]; do
-	case "$1" in
-		"-d" | "--distro" ) distro="$2"; shift 2 ;;
-		"-p" | "--port" ) ports+=("$2"); shift 2 ;;
-		"-m" | "--mount" ) mounts+=("$2"); shift 2 ;;
-		"-r" | "--restart" ) restart="1"; shift 1 ;;
-		* ) name="$1"; shift 1 ;;
-	esac
+    case "$1" in
+        "-d" | "--distro" ) distro="$2"; shift 2 ;;
+        "-p" | "--port" ) ports+=("$2"); shift 2 ;;
+        "-m" | "--mount" ) mounts+=("$2"); shift 2 ;;
+        "-r" | "--restart" ) restart="1"; shift 1 ;;
+        * ) name="$1"; shift 1 ;;
+    esac
 done
 
 if [ -z "$name" ]; then
-	printf "instance name required\n" >&2
-	exit 1
+    printf "instance name required\n" >&2
+    exit 1
 fi
 
 vm_dir="$MKVM_ROOT/machines/$name"
@@ -35,15 +35,15 @@ vm_vfile="$vm_dir/Vagrantfile"
 src_vfile="$MKVM_BIN/../resources/Vagrantfile"
 
 if [ -f "$boxname_file" ]; then
-	if [ -n "$distro" ]; then
-		printf "cannot change distribution without recreating the virtual machine\n" >&2
-		exit 1
-	fi
-	box_name="$(cat "$boxname_file")"
+    if [ -n "$distro" ]; then
+        printf "cannot change distribution without recreating the virtual machine\n" >&2
+        exit 1
+    fi
+    box_name="$(cat "$boxname_file")"
 else
-	mkdir -p "$vm_dir"
-	box_name="${BOXES["${distro:-$DEFAULT_DISTRO}"]}"
-	cat <<<"$box_name" > "$boxname_file"
+    mkdir -p "$vm_dir"
+    box_name="${BOXES["${distro:-$DEFAULT_DISTRO}"]}"
+    cat <<<"$box_name" > "$boxname_file"
 fi
 
 extra=""
@@ -51,28 +51,28 @@ extra+="ports, mounts = [], []"$'\n'
 extra+="box_name = \"$box_name\""$'\n'
 extra+="vm_name = \"$name\""$'\n'
 for port in "${ports[@]}"; do
-	if [[ "$port" =~ ":" ]]; then
-		src="$(cut -d : -f 1 <<<"$port")"
-		dest="$(cut -d : -f 2 <<<"$port")"
-	else
-		src="$port"
-		dest="$port"
-	fi
-	printf "port: %s -> %s\n" "$src" "$dest"
-	extra+="ports << [$src, $dest]"$'\n'
+    if [[ "$port" =~ ":" ]]; then
+        src="$(cut -d : -f 1 <<<"$port")"
+        dest="$(cut -d : -f 2 <<<"$port")"
+    else
+        src="$port"
+        dest="$port"
+    fi
+    printf "port: %s -> %s\n" "$src" "$dest"
+    extra+="ports << [$src, $dest]"$'\n'
 done
 for mount in "${mounts[@]}"; do
-	src="$(cut -d : -f 1 <<<"$mount")"
-	dest="$(cut -d : -f 2 <<<"$mount")"
-	printf "mount: %s -> %s\n" "$src" "$dest"
-	src="$(readlink -f "$src")"
-	extra+="mounts << [\"$src\", \"$dest\"]"$'\n'
+    src="$(cut -d : -f 1 <<<"$mount")"
+    dest="$(cut -d : -f 2 <<<"$mount")"
+    printf "mount: %s -> %s\n" "$src" "$dest"
+    src="$(readlink -f "$src")"
+    extra+="mounts << [\"$src\", \"$dest\"]"$'\n'
 done
 
 mkdir -p "$vm_dir"
 cat - "$src_vfile" <<<"$extra" > "$vm_vfile"
 cd "$vm_dir"
 if [ -n "$restart" ]; then
-	vagrant halt
+    vagrant halt
 fi
 vagrant up
