Support "$MKVM_INSTANCE" to specify default VM instance

diff --git a/bin/mkvm-rm b/bin/mkvm-rm
--- a/bin/mkvm-rm
+++ b/bin/mkvm-rm
@@ -1,11 +1,17 @@
-#!/bin/sh
+#!/bin/bash
 
 set -ue
 
-for arg in "$@"; do
-	vm_dir="$MKVM_ROOT/machines/$arg"
+instances=("$@")
+
+if [ "${#instances[@]}" -eq 0 ] && [ -n "${MKVM_INSTANCE:-}" ]; then
+	instances+=("$MKVM_INSTANCE")
+fi
+
+for instance in "${instances[@]}"; do
+	vm_dir="$MKVM_ROOT/machines/$instance"
 	if [ ! -d "$vm_dir" ]; then
-		printf "machine not found: %s\n" "$arg" >&2
+		printf "machine not found: %s\n" "$instance" >&2
 		exit 1
 	fi
 	(cd "$vm_dir" && vagrant destroy)
diff --git a/bin/mkvm-start b/bin/mkvm-start
--- a/bin/mkvm-start
+++ b/bin/mkvm-start
@@ -8,7 +8,7 @@ declare -A BOXES=(
 	["ubuntu"]="ubuntu/focal64"
 )
 
-name=""
+name="${MKVM_INSTANCE:-}"
 distro=""
 ports=()
 mounts=()
@@ -21,6 +21,11 @@ while [ "$#" -ne 0 ]; do
 		* ) name="$1"; shift 1 ;;
 	esac
 done
+
+if [ -z "$name" ]; then
+	printf "instance name required\n" >&2
+	exit 1
+fi
 
 vm_dir="$MKVM_ROOT/machines/$name"
 boxname_file="$vm_dir/.boxname"
